int fibonacci(int n);
int _2n(int n);
int _an(int a, int n);
int sum(int n);
int fn(int n);
int multInt(int v1, int v2);
int polindromo(std::string s);
int contaCaractere(char c, std::string s);
int somaDigitos(int numero);
int inverteInteiro(int numero);
int imprimeLista(int inicio, int fim);
int maximoDivisor(int a, int b);
int maiorElemento(std::vector<int> v);
int buscaElementoVetor(std::vector<int> v, int elemento);